# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialLoginTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialLoginTest
  pod 'naveridlogin-sdk-ios'

end
